### PR TITLE
Use version 2 of the pagespeed api

### PR DESCRIPTION
**Pull request by timgws**

### CODE REVIEW

**Comment by sgrodzicki** [comment]
@timgws first of all: thanks for getting involved! Could you please fix these broken tests? Why do you propose to dismiss the usage of an API key?

**Comment by timgws** [comment]
@sgrodzicki I am working now on fixing up the tests now, as per https://developers.google.com/speed/docs/insights/v2/reference/pagespeedapi/runpagespeed there is no need with version 2 to provide an API key.

**Comment by timgws** [comment]
I am having issues getting phpunit to run in my environment for this project, all the tests are being skipped.

**Comment by timgws** [comment]
@sgrodzicki I have fixed all the tests. The skips were because of the dependancy on testApiKey (which I have now correctly removed) along with all the @depends docblocks.

**Comment by sgrodzicki** [comment]
Can you delete the constructor and `setUp()` as well? As the key is not needed anymore it shouldn't appear anywhere.

**Comment by timgws** [comment]
@sgrodzicki this has been done. Note that I left the constructor on PageSpeed\Insights\Service.

**Comment by sgrodzicki** [comment]
Why did you left the constructor? It's the default behavior.

**Comment by timgws** [comment]
> It's the default behavior

Oh, in that case, I will put it back :)

**Comment by timgws** [comment]
Noted, it has now been removed.

**Comment by sgrodzicki** [comment]
Thanks @timgws!

**Pull request merged**
